#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker01"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c3bb1a78fb8a47118eaf04b5acfb7a3a" }
]

[assets]
directory = "./public"
